deploy:
  stage: deploy
  tags:
    - eschool
  script:
    - cd /home/ict/www/orbit-project/web-frontend
    - git pull origin main --rebase
    - git checkout remotes/origin/main
    - docker-compose -f ../docker-compose.yml build frontend
    - docker-compose -f ../docker-compose.yml up -d frontend
  only:
    - main
