interface Props {
  title: string;
}

export default function Head({ title }: Props) {
  return (
    <>
      <title>ORBIT - {title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="Orbit.ico" />
    </>
  );
}
